language: cpp
compiler: gcc

os: linux
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-9

script:
  - export CC=gcc-9
  - export CXX=g++-9
  - cmake --version
  - mkdir -p build/cpu-release
  - cmake -DCMAKE_BUILD_TYPE=Release -DGPU=OFF -Bbuild/cpu-release
  - cmake --build build/cpu-release
  - cd build/cpu-release
  - ctest
  - cd ../..